"""
Step 1 demo/test script: Folder picker + scanner + JSON cache builder.

This is a minimal console-driven runner so you can verify the scanning
and caching logic works correctly BEFORE any GUI exists. Run it, point
it at a folder full of music, and inspect the printed summary plus the
generated library_cache.json file.

Usage:
    python step1_demo.py /path/to/your/music/folder [more folders...]

If no folder is given, it defaults to the bundled test_music/ folder
(generated by generate_test_files.py) so you can verify behavior
immediately without needing real music files.
"""

import os
import sys
import json

from core.library_cache import LibraryCache
from core.scanner import scan_folders

CACHE_PATH = os.path.join(os.path.dirname(__file__), "library_cache.json")


def progress(current: int, total: int, filename: str) -> None:
    print(f"  [{current}/{total}] Scanning: {filename}")


def format_duration(seconds: float) -> str:
    if seconds <= 0:
        return "--:--"
    m, s = divmod(int(seconds), 60)
    return f"{m}:{s:02d}"


def main():
    folders = sys.argv[1:]
    if not folders:
        default = os.path.join(os.path.dirname(__file__), "test_music")
        print(f"No folder argument given -- using bundled test folder:\n  {default}\n")
        folders = [default]

    folders = [os.path.abspath(f) for f in folders]
    for f in folders:
        if not os.path.isdir(f):
            print(f"WARNING: '{f}' is not a valid directory, skipping.")

    cache = LibraryCache(CACHE_PATH)
    cache.load()  # picks up any previously-scanned tracks (dedup test)

    cache.settings.music_folders = list(
        set(cache.settings.music_folders) | set(folders)
    )

    print(f"Scanning {len(folders)} folder(s)...\n")
    summary = scan_folders(cache, folders, progress_callback=progress)

    cache.save()

    print("\n" + "=" * 60)
    print("SCAN SUMMARY")
    print("=" * 60)
    print(f"  Files found:    {summary['total_found']}")
    print(f"  New tracks:     {summary['added']}")
    print(f"  Already cached: {summary['skipped']}")
    print(f"  Missing files:  {len(summary['missing'])}")
    if summary["missing"]:
        for m in summary["missing"]:
            print(f"    - {m}")

    print("\n" + "=" * 60)
    print(f"LIBRARY CONTENTS ({len(cache.tracks)} total tracks)")
    print("=" * 60)

    # Group by album_key to preview how the Album page (Step 5) will see this data
    albums: dict[str, list] = {}
    for track in cache.tracks.values():
        albums.setdefault(track.album_key, []).append(track)

    for album_key, tracks in sorted(albums.items()):
        album_name = tracks[0].album
        album_artists = ", ".join(tracks[0].album_artists)
        print(f"\n  Album: {album_name}  —  {album_artists}")
        # Sort exactly like the Album page will: disc, then track number, then name
        tracks_sorted = sorted(
            tracks,
            key=lambda t: (t.disc_number, t.track_number if t.track_number is not None else 9999, t.title),
        )
        for t in tracks_sorted:
            disc_track = f"D{t.disc_number}"
            disc_track += f" T{t.track_number}" if t.track_number is not None else " T-"
            art = "🖼" if t.has_embedded_art else "  "
            missing = " [FILE NOT FOUND]" if t.file_missing else ""
            print(
                f"    [{disc_track}] {art} {t.title:<25} "
                f"by {', '.join(t.artists):<30} ({format_duration(t.duration)}){missing}"
            )

    print(f"\nCache written to: {CACHE_PATH}")
    print("\nDone. Open library_cache.json to inspect the raw structure.")


if __name__ == "__main__":
    main()
